---
title: 'Mixed-effects models'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
---

# Factor levels and 2 subsets

```{r}
pdat[, meas.level := paste(meas.tech, meas.tech.det, treat)]
pdat[, meas.level := gsub('bLS Alpha samplers.+$', 'bLS-alpha', meas.level)]
pdat[, meas.level := gsub('DTM.+$', 'DTM', meas.level)]
pdat[, meas.level := gsub('Wind tunnel NA', 'WT', meas.level)]
pdat[, meas.level := gsub('bLS NA eGylle_bLS', 'bLS-CRDS', meas.level)]
pdat[, meas.level := gsub('.+_FC_.+$', 'FC', meas.level)]
pdat[, meas.level := gsub('diluted$', '', meas.level)]
pdat[, meas.level := gsub('_traps_.+m$', '', meas.level)]
d1 <- pdat[country == 'DK', ]
d2 <- pdat[country == 'NL', ]
```

# I-AU micromet

```{r}
d1mm <- d1[meas.tech2 == 'micro met', ]
d1mm[, .(pmid, meas.level, e.rel.168)]
d1mm[, .(pmid, meas.level, e.rel.final)]
table(d1mm[, meas.level])
```

```{r}
m1 <- lmer(e.rel.168 ~ 1|meas.level, data = d1mm)
summary(m1)
VarCorr(m1)
```

```{r}
m2 <- lmer(log10(e.rel.168) ~ 1|meas.level, data = d1mm)
summary(m2)
VarCorr(m2)
100 * (10^(as.data.frame(VarCorr(m2))[, 5]) - 1)
```

Total.

```{r}
sqrt(sum(as.data.frame(VarCorr(m2))[, 5]^2))
```

# I-AU enclosure

```{r}
d1en <- d1[meas.tech2 != 'micro met', ]
d1en[, .(pmid, meas.level, e.rel.168)]
d1en[, .(pmid, meas.level, e.rel.final)]
table(d1en[, meas.level])
```

```{r}
m1 <- lmer(e.rel.168 ~ 1|meas.level, data = d1en)
summary(m1)
VarCorr(m1)
```

```{r}
m2 <- lmer(log10(e.rel.168) ~ 1|meas.level, data = d1en)
summary(m2)
VarCorr(m2)
100 * (10^(as.data.frame(VarCorr(m2))[, 5]) - 1)
```

Total.

```{r}
sqrt(sum(as.data.frame(VarCorr(m2))[, 5]^2))
```

# I-AU enclosure without DTM

```{r}
d1en <- d1[!meas.tech2 %in% c('micro met', 'DTM'), ]
d1en[, .(pmid, meas.level, e.rel.168)]
d1en[, .(pmid, meas.level, e.rel.final)]
table(d1en[, meas.level])
```

```{r}
m1 <- lmer(e.rel.168 ~ 1|meas.level, data = d1en)
summary(m1)
VarCorr(m1)
```

```{r}
m2 <- lmer(log10(e.rel.168) ~ 1|meas.level, data = d1en)
summary(m2)
VarCorr(m2)
100 * (10^(as.data.frame(VarCorr(m2))[, 5]) - 1)
```

Total.

```{r}
sqrt(sum(as.data.frame(VarCorr(m2))[, 5]^2))
```

# II-WUR micromet

```{r}
d2mm <- d2[meas.tech2 == 'micro met', ]
d2mm[, .(pmid, meas.level, e.rel.168)]
d2mm[, .(pmid, meas.level, e.rel.final)]
table(d2mm[, meas.level])
```

```{r}
m1 <- lmer(e.rel.final ~ 1|meas.level, data = d2mm)
summary(m1)
VarCorr(m1)
```

```{r}
m2 <- lmer(log10(e.rel.final) ~ 1|meas.level, data = d2mm)
summary(m2)
VarCorr(m2)
100 * (10^(as.data.frame(VarCorr(m2))[, 5]) - 1)
```

```{r}
sqrt(sum(as.data.frame(VarCorr(m2))[, 5]^2))
```

Total.

```{r}
sqrt(sum(as.data.frame(VarCorr(m2))[, 5]^2))
```

# II-WUR enclosure

Note that AER was 25 for all WT ("20" is application rate).

```{r}
d2en <- d2[meas.tech2 != 'micro met' & meas.level %in% c('WT 20', 'FC') & !grepl('diluted', treat), ]
d2en[, .(pmid, meas.level, e.rel.168)]
d2en[, .(pmid, meas.level, e.rel.final)]
table(d2en[, meas.level])
```

```{r}
d2en[, .(meas.tech.orig, e.rel.168)]
d2en[, .(meas.level, e.rel.168)]
d2en[, .(meas.level, e.rel.final)]
```

```{r}
m1 <- lmer(e.rel.final ~ 1|meas.level, data = d2en)
summary(m1)
VarCorr(m1)
```

```{r}
m2 <- lmer(log10(e.rel.final) ~ 1|meas.level, data = d2en)
summary(m2)
VarCorr(m2)
100 * (10^(as.data.frame(VarCorr(m2))[, 5]) - 1)
```

Total.

```{r}
sqrt(sum(as.data.frame(VarCorr(m2))[, 5]^2))
```


